name: Zip Creator

on:
  push:

jobs:
  create-zip:
    name: Build and Create Downloadable Zip
    runs-on: ubuntu-latest
    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - uses: pnpm/action-setup@v4.1.0
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: current
          cache: 'pnpm'
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install
        working-directory: web

      - name: Run build
        run: pnpm build
        working-directory: web
        env:
          CI: false

      - name: Bundle files
        run: |
          mkdir -p ./temp/ox_lib
          mkdir -p ./temp/ox_lib/web/
          mkdir -p ./temp/ox_lib/locales/
          cp ./{fxmanifest.lua,init.lua} ./temp/ox_lib
          cp ./{locales/en.json,locales/fr.json} ./temp/ox_lib/locales
          cp -r ./{imports,resource} ./temp/ox_lib
          cp -r ./web/build ./temp/ox_lib/web/
          cd ./temp && zip -r ../ox_lib.zip ./ox_lib

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          automatic_release_tag: "latest"
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Ready to download'
          prerelease: true
          files: ox_lib.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}